# Generated by Django 4.0 on 2022-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_activity_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
